### ISSUE TITLE
How to prevent downloading node modules again and again?

### ISSUE THREAD

**Issue by codestellar** [johnpapa/angular2-force#3]
I have started with [angular2-quickstart](https://github.com/angular/quickstart/) and then came to this. One major issue is I have to download again and again when I switch from one working directory to other.

**Comment by dcaballeroc** [comment]
It's a common pattern on NodeJS applications to have all your dependencies listed in your project's `package.json`, which get installed in the `node_modules` directory inside your project; so yes, it's expected you run a `npm install` on each different NodeJS project you have. Furthermore, if you have all your project's dependencies installed, NPM won't install them again with a simple `npm install`, it'll only install the ones you have not installed yet but are listed in your project's `package.json`.

If you MUST run `npm install` each time you switch between projects to make them work, then you have other sort of problems related with NodeJS or NPM itself, beats me which, but I think is not your case since installing all your dependencies with `npm install` once should be enough.
